import type { Program } from "./types"

export const mockPrograms: Program[] = [
  {
    id: "1",
    name: "SAT Preparation",
    description: "Comprehensive SAT prep covering all sections with full-length practice tests.",
    duration: "12 weeks",
    price: 1999,
    level: "Beginner",
    enrolled: 156,
    maxCapacity: 200,
    instructors: ["Sarah Chen", "James Mitchell"],
    syllabus: "Reading & Writing, Math, Essay Writing, Practice Tests",
  },
  {
    id: "2",
    name: "ACT Preparation",
    description: "Intensive ACT course with focus on time management and strategic problem-solving.",
    duration: "10 weeks",
    price: 1699,
    level: "Beginner",
    enrolled: 98,
    maxCapacity: 150,
    instructors: ["Dr. Robert Lee"],
    syllabus: "English, Math, Reading, Science, Writing",
  },
  {
    id: "3",
    name: "IELTS Preparation",
    description: "Master English proficiency with IELTS-focused instruction and real exam simulations.",
    duration: "8 weeks",
    price: 1299,
    level: "Intermediate",
    enrolled: 124,
    maxCapacity: 180,
    instructors: ["Emma Rodriguez", "David Smith"],
    syllabus: "Speaking, Writing, Reading, Listening, Mock Tests",
  },
  {
    id: "4",
    name: "Essay Writing Masterclass",
    description: "Learn to write compelling university essays that stand out to admissions officers.",
    duration: "6 weeks",
    price: 899,
    level: "Intermediate",
    enrolled: 76,
    maxCapacity: 100,
    instructors: ["Lisa Wang"],
    syllabus: "Story Structure, Personal Essays, Narrative Techniques, Editing",
  },
  {
    id: "5",
    name: "Interview Preparation",
    description: "Master university interview skills with mock interviews and expert coaching.",
    duration: "4 weeks",
    price: 699,
    level: "Advanced",
    enrolled: 45,
    maxCapacity: 80,
    instructors: ["Michael Chen"],
    syllabus: "Interview Techniques, Mock Interviews, Q&A Practice, Body Language",
  },
]
